// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/adapter_information.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AdapterInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdapterInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdapterInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdapterInformationMultiError, or nil if none found.
func (m *AdapterInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *AdapterInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if m.DisplayName != nil {
		// no validation rules for DisplayName
	}

	if m.InputDataSchema != nil {
		// no validation rules for InputDataSchema
	}

	if m.InputDataForm != nil {
		// no validation rules for InputDataForm
	}

	if len(errors) > 0 {
		return AdapterInformationMultiError(errors)
	}

	return nil
}

// AdapterInformationMultiError is an error wrapping multiple validation errors
// returned by AdapterInformation.ValidateAll() if the designated constraints
// aren't met.
type AdapterInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdapterInformationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdapterInformationMultiError) AllErrors() []error { return m }

// AdapterInformationValidationError is the validation error returned by
// AdapterInformation.Validate if the designated constraints aren't met.
type AdapterInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdapterInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdapterInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdapterInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdapterInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdapterInformationValidationError) ErrorName() string {
	return "AdapterInformationValidationError"
}

// Error satisfies the builtin error interface
func (e AdapterInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdapterInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdapterInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdapterInformationValidationError{}
