// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: teamcloud/v1/adapter_service.proto

package teamcloudv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdapterAPIClient is the client API for AdapterAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterAPIClient interface {
	GetAdapters(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdapterInformationListDataResult, error)
}

type adapterAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterAPIClient(cc grpc.ClientConnInterface) AdapterAPIClient {
	return &adapterAPIClient{cc}
}

func (c *adapterAPIClient) GetAdapters(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdapterInformationListDataResult, error) {
	out := new(AdapterInformationListDataResult)
	err := c.cc.Invoke(ctx, "/colbylwilliams.teamcloud.v1.AdapterAPI/GetAdapters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterAPIServer is the server API for AdapterAPI service.
// All implementations should embed UnimplementedAdapterAPIServer
// for forward compatibility
type AdapterAPIServer interface {
	GetAdapters(context.Context, *emptypb.Empty) (*AdapterInformationListDataResult, error)
}

// UnimplementedAdapterAPIServer should be embedded to have forward compatible implementations.
type UnimplementedAdapterAPIServer struct {
}

func (UnimplementedAdapterAPIServer) GetAdapters(context.Context, *emptypb.Empty) (*AdapterInformationListDataResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdapters not implemented")
}

// UnsafeAdapterAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterAPIServer will
// result in compilation errors.
type UnsafeAdapterAPIServer interface {
	mustEmbedUnimplementedAdapterAPIServer()
}

func RegisterAdapterAPIServer(s grpc.ServiceRegistrar, srv AdapterAPIServer) {
	s.RegisterService(&AdapterAPI_ServiceDesc, srv)
}

func _AdapterAPI_GetAdapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterAPIServer).GetAdapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colbylwilliams.teamcloud.v1.AdapterAPI/GetAdapters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterAPIServer).GetAdapters(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterAPI_ServiceDesc is the grpc.ServiceDesc for AdapterAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "colbylwilliams.teamcloud.v1.AdapterAPI",
	HandlerType: (*AdapterAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdapters",
			Handler:    _AdapterAPI_GetAdapters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teamcloud/v1/adapter_service.proto",
}
