// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/component_templates_service.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetComponentTemplateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetComponentTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetComponentTemplateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetComponentTemplateRequestMultiError, or nil if none found.
func (m *GetComponentTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetComponentTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for OrganizationId

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return GetComponentTemplateRequestMultiError(errors)
	}

	return nil
}

// GetComponentTemplateRequestMultiError is an error wrapping multiple
// validation errors returned by GetComponentTemplateRequest.ValidateAll() if
// the designated constraints aren't met.
type GetComponentTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetComponentTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetComponentTemplateRequestMultiError) AllErrors() []error { return m }

// GetComponentTemplateRequestValidationError is the validation error returned
// by GetComponentTemplateRequest.Validate if the designated constraints
// aren't met.
type GetComponentTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetComponentTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetComponentTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetComponentTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetComponentTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetComponentTemplateRequestValidationError) ErrorName() string {
	return "GetComponentTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetComponentTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetComponentTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetComponentTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetComponentTemplateRequestValidationError{}

// Validate checks the field values on GetComponentTemplatesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetComponentTemplatesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetComponentTemplatesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetComponentTemplatesRequestMultiError, or nil if none found.
func (m *GetComponentTemplatesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetComponentTemplatesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return GetComponentTemplatesRequestMultiError(errors)
	}

	return nil
}

// GetComponentTemplatesRequestMultiError is an error wrapping multiple
// validation errors returned by GetComponentTemplatesRequest.ValidateAll() if
// the designated constraints aren't met.
type GetComponentTemplatesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetComponentTemplatesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetComponentTemplatesRequestMultiError) AllErrors() []error { return m }

// GetComponentTemplatesRequestValidationError is the validation error returned
// by GetComponentTemplatesRequest.Validate if the designated constraints
// aren't met.
type GetComponentTemplatesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetComponentTemplatesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetComponentTemplatesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetComponentTemplatesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetComponentTemplatesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetComponentTemplatesRequestValidationError) ErrorName() string {
	return "GetComponentTemplatesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetComponentTemplatesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetComponentTemplatesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetComponentTemplatesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetComponentTemplatesRequestValidationError{}
