// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/component_task_runner.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ComponentTaskRunner with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ComponentTaskRunner) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ComponentTaskRunner with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ComponentTaskRunnerMultiError, or nil if none found.
func (m *ComponentTaskRunner) ValidateAll() error {
	return m.validate(true)
}

func (m *ComponentTaskRunner) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WebServer

	// no validation rules for With

	if m.Id != nil {
		// no validation rules for Id
	}

	if len(errors) > 0 {
		return ComponentTaskRunnerMultiError(errors)
	}

	return nil
}

// ComponentTaskRunnerMultiError is an error wrapping multiple validation
// errors returned by ComponentTaskRunner.ValidateAll() if the designated
// constraints aren't met.
type ComponentTaskRunnerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ComponentTaskRunnerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ComponentTaskRunnerMultiError) AllErrors() []error { return m }

// ComponentTaskRunnerValidationError is the validation error returned by
// ComponentTaskRunner.Validate if the designated constraints aren't met.
type ComponentTaskRunnerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ComponentTaskRunnerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ComponentTaskRunnerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ComponentTaskRunnerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ComponentTaskRunnerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ComponentTaskRunnerValidationError) ErrorName() string {
	return "ComponentTaskRunnerValidationError"
}

// Error satisfies the builtin error interface
func (e ComponentTaskRunnerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sComponentTaskRunner.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ComponentTaskRunnerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ComponentTaskRunnerValidationError{}
