//
//TeamCloud
//
//API for working with a TeamCloud instance.
//
//The version of the OpenAPI document: v1
//
//Contact: colbyw@microsoft.com
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: teamcloud/v1/component_template_permissions.proto

package teamcloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentTemplatePermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	None    []string `protobuf:"bytes,2433880,rep,name=None,proto3" json:"None,omitempty"`
	Member  []string `protobuf:"bytes,383289673,rep,name=Member,proto3" json:"Member,omitempty"`
	Admin   []string `protobuf:"bytes,63116079,rep,name=Admin,proto3" json:"Admin,omitempty"`
	Owner   []string `protobuf:"bytes,76612243,rep,name=Owner,proto3" json:"Owner,omitempty"`
	Adapter []string `protobuf:"bytes,514145071,rep,name=Adapter,proto3" json:"Adapter,omitempty"`
}

func (x *ComponentTemplatePermissions) Reset() {
	*x = ComponentTemplatePermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teamcloud_v1_component_template_permissions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentTemplatePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentTemplatePermissions) ProtoMessage() {}

func (x *ComponentTemplatePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_teamcloud_v1_component_template_permissions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentTemplatePermissions.ProtoReflect.Descriptor instead.
func (*ComponentTemplatePermissions) Descriptor() ([]byte, []int) {
	return file_teamcloud_v1_component_template_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentTemplatePermissions) GetNone() []string {
	if x != nil {
		return x.None
	}
	return nil
}

func (x *ComponentTemplatePermissions) GetMember() []string {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *ComponentTemplatePermissions) GetAdmin() []string {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *ComponentTemplatePermissions) GetOwner() []string {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ComponentTemplatePermissions) GetAdapter() []string {
	if x != nil {
		return x.Adapter
	}
	return nil
}

var File_teamcloud_v1_component_template_permissions_proto protoreflect.FileDescriptor

var file_teamcloud_v1_component_template_permissions_proto_rawDesc = []byte{
	0x0a, 0x31, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x63, 0x6f, 0x6c, 0x62, 0x79, 0x6c, 0x77, 0x69, 0x6c, 0x6c, 0x69,
	0x61, 0x6d, 0x73, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x31,
	0x22, 0xa1, 0x01, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x15, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x18, 0xd8, 0xc6, 0x94, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0xc9, 0x92, 0xe2, 0xb6, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0xaf, 0xa6,
	0x8c, 0x1e, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x17, 0x0a,
	0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x93, 0x85, 0xc4, 0x24, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x07, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x18, 0xaf, 0xf6, 0x94, 0xf5, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x42, 0x59, 0x5a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6c, 0x62, 0x79, 0x6c, 0x77, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x6d,
	0x73, 0x2f, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x76, 0x31, 0x3b, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teamcloud_v1_component_template_permissions_proto_rawDescOnce sync.Once
	file_teamcloud_v1_component_template_permissions_proto_rawDescData = file_teamcloud_v1_component_template_permissions_proto_rawDesc
)

func file_teamcloud_v1_component_template_permissions_proto_rawDescGZIP() []byte {
	file_teamcloud_v1_component_template_permissions_proto_rawDescOnce.Do(func() {
		file_teamcloud_v1_component_template_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_teamcloud_v1_component_template_permissions_proto_rawDescData)
	})
	return file_teamcloud_v1_component_template_permissions_proto_rawDescData
}

var file_teamcloud_v1_component_template_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_teamcloud_v1_component_template_permissions_proto_goTypes = []interface{}{
	(*ComponentTemplatePermissions)(nil), // 0: colbylwilliams.teamcloud.v1.ComponentTemplatePermissions
}
var file_teamcloud_v1_component_template_permissions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teamcloud_v1_component_template_permissions_proto_init() }
func file_teamcloud_v1_component_template_permissions_proto_init() {
	if File_teamcloud_v1_component_template_permissions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teamcloud_v1_component_template_permissions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentTemplatePermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teamcloud_v1_component_template_permissions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teamcloud_v1_component_template_permissions_proto_goTypes,
		DependencyIndexes: file_teamcloud_v1_component_template_permissions_proto_depIdxs,
		MessageInfos:      file_teamcloud_v1_component_template_permissions_proto_msgTypes,
	}.Build()
	File_teamcloud_v1_component_template_permissions_proto = out.File
	file_teamcloud_v1_component_template_permissions_proto_rawDesc = nil
	file_teamcloud_v1_component_template_permissions_proto_goTypes = nil
	file_teamcloud_v1_component_template_permissions_proto_depIdxs = nil
}
