// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/deployment_scope.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeploymentScope with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeploymentScope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeploymentScope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeploymentScopeMultiError, or nil if none found.
func (m *DeploymentScope) ValidateAll() error {
	return m.validate(true)
}

func (m *DeploymentScope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Organization

	// no validation rules for OrganizationName

	// no validation rules for DisplayName

	// no validation rules for Slug

	// no validation rules for IsDefault

	// no validation rules for Type

	// no validation rules for Authorizable

	// no validation rules for Authorized

	// no validation rules for ComponentTypes

	// no validation rules for Id

	if m.InputDataSchema != nil {
		// no validation rules for InputDataSchema
	}

	if m.InputData != nil {
		// no validation rules for InputData
	}

	if m.ManagementGroupId != nil {
		// no validation rules for ManagementGroupId
	}

	if m.AuthorizeUrl != nil {
		// no validation rules for AuthorizeUrl
	}

	if len(errors) > 0 {
		return DeploymentScopeMultiError(errors)
	}

	return nil
}

// DeploymentScopeMultiError is an error wrapping multiple validation errors
// returned by DeploymentScope.ValidateAll() if the designated constraints
// aren't met.
type DeploymentScopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeploymentScopeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeploymentScopeMultiError) AllErrors() []error { return m }

// DeploymentScopeValidationError is the validation error returned by
// DeploymentScope.Validate if the designated constraints aren't met.
type DeploymentScopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeploymentScopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeploymentScopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeploymentScopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeploymentScopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeploymentScopeValidationError) ErrorName() string { return "DeploymentScopeValidationError" }

// Error satisfies the builtin error interface
func (e DeploymentScopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeploymentScope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeploymentScopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeploymentScopeValidationError{}
