// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/project_identity.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProjectIdentity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProjectIdentity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectIdentity with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectIdentityMultiError, or nil if none found.
func (m *ProjectIdentity) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectIdentity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for ProjectName

	// no validation rules for Organization

	// no validation rules for OrganizationName

	// no validation rules for DisplayName

	// no validation rules for DeploymentScopeId

	// no validation rules for TenantId

	// no validation rules for ClientId

	// no validation rules for ObjectId

	// no validation rules for Id

	if m.ClientSecret != nil {
		// no validation rules for ClientSecret
	}

	if len(errors) > 0 {
		return ProjectIdentityMultiError(errors)
	}

	return nil
}

// ProjectIdentityMultiError is an error wrapping multiple validation errors
// returned by ProjectIdentity.ValidateAll() if the designated constraints
// aren't met.
type ProjectIdentityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectIdentityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectIdentityMultiError) AllErrors() []error { return m }

// ProjectIdentityValidationError is the validation error returned by
// ProjectIdentity.Validate if the designated constraints aren't met.
type ProjectIdentityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectIdentityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectIdentityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectIdentityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectIdentityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectIdentityValidationError) ErrorName() string { return "ProjectIdentityValidationError" }

// Error satisfies the builtin error interface
func (e ProjectIdentityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectIdentity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectIdentityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectIdentityValidationError{}
