// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/project_template.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProjectTemplate with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProjectTemplate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTemplate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTemplateMultiError, or nil if none found.
func (m *ProjectTemplate) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTemplate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Organization

	// no validation rules for OrganizationName

	// no validation rules for Slug

	// no validation rules for DisplayName

	if all {
		switch v := interface{}(m.GetRepository()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProjectTemplateValidationError{
					field:  "Repository",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProjectTemplateValidationError{
					field:  "Repository",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRepository()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectTemplateValidationError{
				field:  "Repository",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsDefault

	// no validation rules for Id

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.InputJsonSchema != nil {
		// no validation rules for InputJsonSchema
	}

	if len(errors) > 0 {
		return ProjectTemplateMultiError(errors)
	}

	return nil
}

// ProjectTemplateMultiError is an error wrapping multiple validation errors
// returned by ProjectTemplate.ValidateAll() if the designated constraints
// aren't met.
type ProjectTemplateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTemplateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTemplateMultiError) AllErrors() []error { return m }

// ProjectTemplateValidationError is the validation error returned by
// ProjectTemplate.Validate if the designated constraints aren't met.
type ProjectTemplateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTemplateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTemplateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTemplateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTemplateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTemplateValidationError) ErrorName() string { return "ProjectTemplateValidationError" }

// Error satisfies the builtin error interface
func (e ProjectTemplateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTemplate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTemplateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTemplateValidationError{}
