// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/schedule_definition.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ScheduleDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ScheduleDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScheduleDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScheduleDefinitionMultiError, or nil if none found.
func (m *ScheduleDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *ScheduleDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enabled

	// no validation rules for Recurring

	// no validation rules for DaysOfWeek

	// no validation rules for UtcHour

	// no validation rules for UtcMinute

	for idx, item := range m.GetComponentTasks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ScheduleDefinitionValidationError{
						field:  fmt.Sprintf("ComponentTasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ScheduleDefinitionValidationError{
						field:  fmt.Sprintf("ComponentTasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ScheduleDefinitionValidationError{
					field:  fmt.Sprintf("ComponentTasks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ScheduleDefinitionMultiError(errors)
	}

	return nil
}

// ScheduleDefinitionMultiError is an error wrapping multiple validation errors
// returned by ScheduleDefinition.ValidateAll() if the designated constraints
// aren't met.
type ScheduleDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScheduleDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScheduleDefinitionMultiError) AllErrors() []error { return m }

// ScheduleDefinitionValidationError is the validation error returned by
// ScheduleDefinition.Validate if the designated constraints aren't met.
type ScheduleDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScheduleDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScheduleDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScheduleDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScheduleDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScheduleDefinitionValidationError) ErrorName() string {
	return "ScheduleDefinitionValidationError"
}

// Error satisfies the builtin error interface
func (e ScheduleDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScheduleDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScheduleDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScheduleDefinitionValidationError{}
