//
//TeamCloud
//
//API for working with a TeamCloud instance.
//
//The version of the OpenAPI document: v1
//
//Contact: colbyw@microsoft.com
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: teamcloud/v1/team_cloud_information.proto

package teamcloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamCloudInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageVersion    *string `protobuf:"bytes,412999422,opt,name=imageVersion,proto3,oneof" json:"imageVersion,omitempty"`
	TemplateVersion *string `protobuf:"bytes,490419459,opt,name=templateVersion,proto3,oneof" json:"templateVersion,omitempty"`
}

func (x *TeamCloudInformation) Reset() {
	*x = TeamCloudInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teamcloud_v1_team_cloud_information_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamCloudInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamCloudInformation) ProtoMessage() {}

func (x *TeamCloudInformation) ProtoReflect() protoreflect.Message {
	mi := &file_teamcloud_v1_team_cloud_information_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamCloudInformation.ProtoReflect.Descriptor instead.
func (*TeamCloudInformation) Descriptor() ([]byte, []int) {
	return file_teamcloud_v1_team_cloud_information_proto_rawDescGZIP(), []int{0}
}

func (x *TeamCloudInformation) GetImageVersion() string {
	if x != nil && x.ImageVersion != nil {
		return *x.ImageVersion
	}
	return ""
}

func (x *TeamCloudInformation) GetTemplateVersion() string {
	if x != nil && x.TemplateVersion != nil {
		return *x.TemplateVersion
	}
	return ""
}

var File_teamcloud_v1_team_cloud_information_proto protoreflect.FileDescriptor

var file_teamcloud_v1_team_cloud_information_proto_rawDesc = []byte{
	0x0a, 0x29, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x63, 0x6f, 0x6c,
	0x62, 0x79, 0x6c, 0x77, 0x69, 0x6c, 0x6c, 0x69, 0x61, 0x6d, 0x73, 0x2e, 0x74, 0x65, 0x61, 0x6d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x9b, 0x01, 0x0a, 0x14, 0x54, 0x65, 0x61,
	0x6d, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0xfe, 0xbd, 0xf7, 0xc4, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x31,
	0x0a, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x83, 0xea, 0xec, 0xe9, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x59, 0x5a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6c, 0x62, 0x79, 0x6c, 0x77, 0x69, 0x6c, 0x6c, 0x69,
	0x61, 0x6d, 0x73, 0x2f, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teamcloud_v1_team_cloud_information_proto_rawDescOnce sync.Once
	file_teamcloud_v1_team_cloud_information_proto_rawDescData = file_teamcloud_v1_team_cloud_information_proto_rawDesc
)

func file_teamcloud_v1_team_cloud_information_proto_rawDescGZIP() []byte {
	file_teamcloud_v1_team_cloud_information_proto_rawDescOnce.Do(func() {
		file_teamcloud_v1_team_cloud_information_proto_rawDescData = protoimpl.X.CompressGZIP(file_teamcloud_v1_team_cloud_information_proto_rawDescData)
	})
	return file_teamcloud_v1_team_cloud_information_proto_rawDescData
}

var file_teamcloud_v1_team_cloud_information_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_teamcloud_v1_team_cloud_information_proto_goTypes = []interface{}{
	(*TeamCloudInformation)(nil), // 0: colbylwilliams.teamcloud.v1.TeamCloudInformation
}
var file_teamcloud_v1_team_cloud_information_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teamcloud_v1_team_cloud_information_proto_init() }
func file_teamcloud_v1_team_cloud_information_proto_init() {
	if File_teamcloud_v1_team_cloud_information_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teamcloud_v1_team_cloud_information_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamCloudInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_teamcloud_v1_team_cloud_information_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teamcloud_v1_team_cloud_information_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teamcloud_v1_team_cloud_information_proto_goTypes,
		DependencyIndexes: file_teamcloud_v1_team_cloud_information_proto_depIdxs,
		MessageInfos:      file_teamcloud_v1_team_cloud_information_proto_msgTypes,
	}.Build()
	File_teamcloud_v1_team_cloud_information_proto = out.File
	file_teamcloud_v1_team_cloud_information_proto_rawDesc = nil
	file_teamcloud_v1_team_cloud_information_proto_goTypes = nil
	file_teamcloud_v1_team_cloud_information_proto_depIdxs = nil
}
