// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/teamcloud.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetTeamCloudInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTeamCloudInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTeamCloudInfoRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTeamCloudInfoRequestMultiError, or nil if none found.
func (m *GetTeamCloudInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTeamCloudInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetTeamCloudInfoRequestMultiError(errors)
	}

	return nil
}

// GetTeamCloudInfoRequestMultiError is an error wrapping multiple validation
// errors returned by GetTeamCloudInfoRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTeamCloudInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTeamCloudInfoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTeamCloudInfoRequestMultiError) AllErrors() []error { return m }

// GetTeamCloudInfoRequestValidationError is the validation error returned by
// GetTeamCloudInfoRequest.Validate if the designated constraints aren't met.
type GetTeamCloudInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTeamCloudInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTeamCloudInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTeamCloudInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTeamCloudInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTeamCloudInfoRequestValidationError) ErrorName() string {
	return "GetTeamCloudInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTeamCloudInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTeamCloudInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTeamCloudInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTeamCloudInfoRequestValidationError{}

// Validate checks the field values on GetTeamCloudInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTeamCloudInfoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTeamCloudInfoResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTeamCloudInfoResponseMultiError, or nil if none found.
func (m *GetTeamCloudInfoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTeamCloudInfoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTeamCloudInfoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTeamCloudInfoResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTeamCloudInfoResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTeamCloudInfoResponseMultiError(errors)
	}

	return nil
}

// GetTeamCloudInfoResponseMultiError is an error wrapping multiple validation
// errors returned by GetTeamCloudInfoResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTeamCloudInfoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTeamCloudInfoResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTeamCloudInfoResponseMultiError) AllErrors() []error { return m }

// GetTeamCloudInfoResponseValidationError is the validation error returned by
// GetTeamCloudInfoResponse.Validate if the designated constraints aren't met.
type GetTeamCloudInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTeamCloudInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTeamCloudInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTeamCloudInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTeamCloudInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTeamCloudInfoResponseValidationError) ErrorName() string {
	return "GetTeamCloudInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTeamCloudInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTeamCloudInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTeamCloudInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTeamCloudInfoResponseValidationError{}

// Validate checks the field values on TeamCloudInfoData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TeamCloudInfoData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TeamCloudInfoData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TeamCloudInfoDataMultiError, or nil if none found.
func (m *TeamCloudInfoData) ValidateAll() error {
	return m.validate(true)
}

func (m *TeamCloudInfoData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ImageVersion

	// no validation rules for TemplateVersion

	if len(errors) > 0 {
		return TeamCloudInfoDataMultiError(errors)
	}

	return nil
}

// TeamCloudInfoDataMultiError is an error wrapping multiple validation errors
// returned by TeamCloudInfoData.ValidateAll() if the designated constraints
// aren't met.
type TeamCloudInfoDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TeamCloudInfoDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TeamCloudInfoDataMultiError) AllErrors() []error { return m }

// TeamCloudInfoDataValidationError is the validation error returned by
// TeamCloudInfoData.Validate if the designated constraints aren't met.
type TeamCloudInfoDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TeamCloudInfoDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TeamCloudInfoDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TeamCloudInfoDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TeamCloudInfoDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TeamCloudInfoDataValidationError) ErrorName() string {
	return "TeamCloudInfoDataValidationError"
}

// Error satisfies the builtin error interface
func (e TeamCloudInfoDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTeamCloudInfoData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TeamCloudInfoDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TeamCloudInfoDataValidationError{}
