// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/team_cloud_information.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TeamCloudInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TeamCloudInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TeamCloudInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TeamCloudInformationMultiError, or nil if none found.
func (m *TeamCloudInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *TeamCloudInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.ImageVersion != nil {
		// no validation rules for ImageVersion
	}

	if m.TemplateVersion != nil {
		// no validation rules for TemplateVersion
	}

	if len(errors) > 0 {
		return TeamCloudInformationMultiError(errors)
	}

	return nil
}

// TeamCloudInformationMultiError is an error wrapping multiple validation
// errors returned by TeamCloudInformation.ValidateAll() if the designated
// constraints aren't met.
type TeamCloudInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TeamCloudInformationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TeamCloudInformationMultiError) AllErrors() []error { return m }

// TeamCloudInformationValidationError is the validation error returned by
// TeamCloudInformation.Validate if the designated constraints aren't met.
type TeamCloudInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TeamCloudInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TeamCloudInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TeamCloudInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TeamCloudInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TeamCloudInformationValidationError) ErrorName() string {
	return "TeamCloudInformationValidationError"
}

// Error satisfies the builtin error interface
func (e TeamCloudInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTeamCloudInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TeamCloudInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TeamCloudInformationValidationError{}
