// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/user_alternate_identities.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserAlternateIdentities with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserAlternateIdentities) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserAlternateIdentities with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserAlternateIdentitiesMultiError, or nil if none found.
func (m *UserAlternateIdentities) ValidateAll() error {
	return m.validate(true)
}

func (m *UserAlternateIdentities) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAzureResourceManager()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "AzureResourceManager",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "AzureResourceManager",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAzureResourceManager()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserAlternateIdentitiesValidationError{
				field:  "AzureResourceManager",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAzureDevOps()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "AzureDevOps",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "AzureDevOps",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAzureDevOps()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserAlternateIdentitiesValidationError{
				field:  "AzureDevOps",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetGitHub()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "GitHub",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "GitHub",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGitHub()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserAlternateIdentitiesValidationError{
				field:  "GitHub",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetKubernetes()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "Kubernetes",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserAlternateIdentitiesValidationError{
					field:  "Kubernetes",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetKubernetes()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserAlternateIdentitiesValidationError{
				field:  "Kubernetes",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserAlternateIdentitiesMultiError(errors)
	}

	return nil
}

// UserAlternateIdentitiesMultiError is an error wrapping multiple validation
// errors returned by UserAlternateIdentities.ValidateAll() if the designated
// constraints aren't met.
type UserAlternateIdentitiesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserAlternateIdentitiesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserAlternateIdentitiesMultiError) AllErrors() []error { return m }

// UserAlternateIdentitiesValidationError is the validation error returned by
// UserAlternateIdentities.Validate if the designated constraints aren't met.
type UserAlternateIdentitiesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserAlternateIdentitiesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserAlternateIdentitiesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserAlternateIdentitiesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserAlternateIdentitiesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserAlternateIdentitiesValidationError) ErrorName() string {
	return "UserAlternateIdentitiesValidationError"
}

// Error satisfies the builtin error interface
func (e UserAlternateIdentitiesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserAlternateIdentities.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserAlternateIdentitiesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserAlternateIdentitiesValidationError{}
