// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: teamcloud/v1/user_projects_service.proto

package teamcloudv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetUserProjectsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserProjectsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserProjectsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserProjectsRequestMultiError, or nil if none found.
func (m *GetUserProjectsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserProjectsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetUserProjectsRequestMultiError(errors)
	}

	return nil
}

// GetUserProjectsRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserProjectsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserProjectsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserProjectsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserProjectsRequestMultiError) AllErrors() []error { return m }

// GetUserProjectsRequestValidationError is the validation error returned by
// GetUserProjectsRequest.Validate if the designated constraints aren't met.
type GetUserProjectsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserProjectsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserProjectsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserProjectsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserProjectsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserProjectsRequestValidationError) ErrorName() string {
	return "GetUserProjectsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserProjectsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserProjectsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserProjectsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserProjectsRequestValidationError{}

// Validate checks the field values on GetUserProjectsMeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserProjectsMeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserProjectsMeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserProjectsMeRequestMultiError, or nil if none found.
func (m *GetUserProjectsMeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserProjectsMeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	if len(errors) > 0 {
		return GetUserProjectsMeRequestMultiError(errors)
	}

	return nil
}

// GetUserProjectsMeRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserProjectsMeRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserProjectsMeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserProjectsMeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserProjectsMeRequestMultiError) AllErrors() []error { return m }

// GetUserProjectsMeRequestValidationError is the validation error returned by
// GetUserProjectsMeRequest.Validate if the designated constraints aren't met.
type GetUserProjectsMeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserProjectsMeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserProjectsMeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserProjectsMeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserProjectsMeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserProjectsMeRequestValidationError) ErrorName() string {
	return "GetUserProjectsMeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserProjectsMeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserProjectsMeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserProjectsMeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserProjectsMeRequestValidationError{}
