// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: teamcloud/v1/user_projects_service.proto

package teamcloudv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserProjectsAPIClient is the client API for UserProjectsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserProjectsAPIClient interface {
	GetUserProjects(ctx context.Context, in *GetUserProjectsRequest, opts ...grpc.CallOption) (*ProjectListDataResult, error)
	GetUserProjectsMe(ctx context.Context, in *GetUserProjectsMeRequest, opts ...grpc.CallOption) (*ProjectListDataResult, error)
}

type userProjectsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProjectsAPIClient(cc grpc.ClientConnInterface) UserProjectsAPIClient {
	return &userProjectsAPIClient{cc}
}

func (c *userProjectsAPIClient) GetUserProjects(ctx context.Context, in *GetUserProjectsRequest, opts ...grpc.CallOption) (*ProjectListDataResult, error) {
	out := new(ProjectListDataResult)
	err := c.cc.Invoke(ctx, "/colbylwilliams.teamcloud.v1.UserProjectsAPI/GetUserProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectsAPIClient) GetUserProjectsMe(ctx context.Context, in *GetUserProjectsMeRequest, opts ...grpc.CallOption) (*ProjectListDataResult, error) {
	out := new(ProjectListDataResult)
	err := c.cc.Invoke(ctx, "/colbylwilliams.teamcloud.v1.UserProjectsAPI/GetUserProjectsMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProjectsAPIServer is the server API for UserProjectsAPI service.
// All implementations should embed UnimplementedUserProjectsAPIServer
// for forward compatibility
type UserProjectsAPIServer interface {
	GetUserProjects(context.Context, *GetUserProjectsRequest) (*ProjectListDataResult, error)
	GetUserProjectsMe(context.Context, *GetUserProjectsMeRequest) (*ProjectListDataResult, error)
}

// UnimplementedUserProjectsAPIServer should be embedded to have forward compatible implementations.
type UnimplementedUserProjectsAPIServer struct {
}

func (UnimplementedUserProjectsAPIServer) GetUserProjects(context.Context, *GetUserProjectsRequest) (*ProjectListDataResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProjects not implemented")
}
func (UnimplementedUserProjectsAPIServer) GetUserProjectsMe(context.Context, *GetUserProjectsMeRequest) (*ProjectListDataResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProjectsMe not implemented")
}

// UnsafeUserProjectsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserProjectsAPIServer will
// result in compilation errors.
type UnsafeUserProjectsAPIServer interface {
	mustEmbedUnimplementedUserProjectsAPIServer()
}

func RegisterUserProjectsAPIServer(s grpc.ServiceRegistrar, srv UserProjectsAPIServer) {
	s.RegisterService(&UserProjectsAPI_ServiceDesc, srv)
}

func _UserProjectsAPI_GetUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectsAPIServer).GetUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colbylwilliams.teamcloud.v1.UserProjectsAPI/GetUserProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectsAPIServer).GetUserProjects(ctx, req.(*GetUserProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectsAPI_GetUserProjectsMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectsMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectsAPIServer).GetUserProjectsMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colbylwilliams.teamcloud.v1.UserProjectsAPI/GetUserProjectsMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectsAPIServer).GetUserProjectsMe(ctx, req.(*GetUserProjectsMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserProjectsAPI_ServiceDesc is the grpc.ServiceDesc for UserProjectsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserProjectsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "colbylwilliams.teamcloud.v1.UserProjectsAPI",
	HandlerType: (*UserProjectsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProjects",
			Handler:    _UserProjectsAPI_GetUserProjects_Handler,
		},
		{
			MethodName: "GetUserProjectsMe",
			Handler:    _UserProjectsAPI_GetUserProjectsMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teamcloud/v1/user_projects_service.proto",
}
