/* eslint-disable */
/*
 * This file is autogenerated. DO NOT MODIFY BY HAND!
 * Run the @clutch-sh/tools registerWorkflows target instead
*/
import { default as ec2} from "@clutch-sh/ec2";
import { default as echo} from "@clutch-teamcloud-gateway/echo";

const registeredWorkflows = {
  "@clutch-sh/ec2": ec2,
  "@clutch-teamcloud-gateway/echo": echo,
};
export default registeredWorkflows;